apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-api
  template:
    metadata:
      labels:
        app: mlops-api
    spec:
      containers:
      - name: mlops-api-container
        image: YOUR_IMAGE_URL # Placeholder
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mlops-api-service
spec:
  type: LoadBalancer # Creates an External IP
  selector:
    app: mlops-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080